# Generated by Django 3.0.5 on 2020-04-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_auto_20200422_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='https://static.thenounproject.com/png/629576-200.png', upload_to='profile_image'),
        ),
    ]
