# Generated by Django 3.0.5 on 2020-04-17 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookedClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gym', models.CharField(max_length=200)),
                ('activity_type', models.CharField(max_length=500)),
                ('instructor', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('time_of_class', models.CharField(max_length=200)),
                ('borough', models.CharField(max_length=200)),
                ('data_booked', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Borough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('facilities', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FitnessClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('activity_type', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('time_of_class', models.CharField(max_length=200)),
                ('borough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness', to='fitness.Borough')),
                ('comment', models.ManyToManyField(blank=True, related_name='fitness', to='fitness.Comment')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness', to='fitness.Gym')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness', to='fitness.Instructor')),
            ],
        ),
        migrations.AddField(
            model_name='borough',
            name='fitnessclass',
            field=models.ManyToManyField(related_name='fitness', to='fitness.FitnessClass'),
        ),
    ]
