# Generated by Django 3.0.5 on 2020-04-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_auto_20200416_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessclass',
            name='comment',
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='fitness', to='fitness.Comment'),
        ),
    ]
