# Generated by Django 3.0.5 on 2020-04-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_auto_20200416_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='borough',
            name='fitnessclass',
            field=models.ManyToManyField(related_name='fitness', to='fitness.FitnessClass'),
        ),
    ]
