# Generated by Django 3.0.5 on 2020-04-17 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_auto_20200417_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedclass',
            name='borough',
        ),
        migrations.RemoveField(
            model_name='fitnessclass',
            name='borough',
        ),
    ]
