# Generated by Django 3.0.5 on 2020-04-17 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitness', '0005_auto_20200417_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessclass',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fitness', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
